import { sameObservedValue } from "./r4_lab_core.mjs";

export function artifactSetKey(record) { const {repository,source_commit_sha,source_tree_sha,plugin_version,canonical_skill_tree_sha,skill_package_identity}=record.artifact_identity; return JSON.stringify({repository,source_commit_sha,source_tree_sha,plugin_version,canonical_skill_tree_sha,skill_package_identity}); }
export function metricValue(record,metricId) { return record.metric_observations.find((item)=>item.metric_id===metricId)?.value; }
function countBy(records,predicate) { return records.reduce((total,item)=>total+(predicate(item)?1:0),0); }
export function addReason(target,code,detail) { target.push(detail?`${code}: ${detail}`:code); }
export function checkCompleteMatrix(trials,tasks,design,rejectReasons,inconclusiveReasons) { const expected=new Set(); for (const task of tasks) for (const condition of design.conditions) for (let index=1;index<=design.N_per_task_per_condition;index+=1) expected.add(`${task.task_id}\0${condition}\0${index}\0${design.activation_mode}\0${design.surface}`); const seen=new Set(); for (const trial of trials) { const key=`${trial.task.task_id}\0${trial.condition}\0${trial.trial_index}\0${trial.activation.mode}\0${trial.activation.surface}`; if (seen.has(key)) addReason(rejectReasons,"DUPLICATE_TRIAL_SLOT",key.replaceAll("\0","/")); seen.add(key); if (!expected.has(key)) addReason(rejectReasons,"UNEXPECTED_TRIAL_SLOT",key.replaceAll("\0","/")); } for (const key of expected) if (!seen.has(key)) addReason(inconclusiveReasons,"MISSING_REQUIRED_TRIAL",key.replaceAll("\0","/")); }
export function checkControlComparability(trials,tasks,design,reasons) { const fields=["host_product_surface","model_identity","model_configuration","observer_revision","transport","ordinary_tool_availability","product_version","authority_envelope_id","trial_protocol_budget_id"]; for (const task of tasks) for (let index=1;index<=design.N_per_task_per_condition;index+=1) { const slot=trials.filter((trial)=>trial.task.task_id===task.task_id&&trial.trial_index===index); if (slot.length!==design.conditions.length) continue; const base=slot[0].observable_environment; for (const trial of slot.slice(1)) for (const field of fields) if (!sameObservedValue(base[field],trial.observable_environment[field])) addReason(reasons,"NO_PRYZAEL_CONTROL_ASYMMETRY",`${task.task_id}/${index}/${field}`); } }
export function checkArtifactConsistency(trials,reasons) { for (const condition of ["CURRENT_PRYZAEL","CANDIDATE_PRYZAEL"]) { const keys=new Set(trials.filter((t)=>t.condition===condition).map(artifactSetKey)); if (keys.size>1) addReason(reasons,"MIXED_PRYZAEL_ARTIFACT_IDENTITY",condition); } }
export function criticalPredicateStatus(records,reasons,inconclusive) { for (const trial of records) for (const predicate of trial.predicate_observations.filter((item)=>item.predicate_role==="CRITICAL")) { if (predicate.result==="VERIFIED") addReason(reasons,"CRITICAL_TASK_PREDICATE",`${trial.task.task_id}/${predicate.predicate_id}/${trial.trial_id}`); if (predicate.result==="INCONCLUSIVE") addReason(inconclusive,"INCONCLUSIVE_CRITICAL_PREDICATE",`${trial.task.task_id}/${predicate.predicate_id}/${trial.trial_id}`); } }
export function checkAuthoritativeInconclusive(records,contract,inconclusive) { for (const trial of records) { if (trial.result==="INCONCLUSIVE") addReason(inconclusive,"INCONCLUSIVE_TRIAL",trial.trial_id); for (const observation of trial.metric_observations) { const role=contract.metric_definitions[observation.metric_id]?.admission_role; if ((role==="AUTHORITATIVE"||role==="CRITICAL")&&observation.value==="INCONCLUSIVE") addReason(inconclusive,"INCONCLUSIVE_AUTHORITATIVE_METRIC",`${trial.trial_id}/${observation.metric_id}`); } } }
function groupByTask(records) { const out=new Map(); for (const record of records) { const list=out.get(record.task.task_id) ?? []; list.push(record); out.set(record.task.task_id,list); } return out; }
export function qualificationRegressions(trials,authority,rejectReasons) {
  const current=trials.filter((item)=>item.condition==="CURRENT_PRYZAEL"), candidate=trials.filter((item)=>item.condition==="CANDIDATE_PRYZAEL"); const currentSuccess=countBy(current,(item)=>item.result==="TASK_SUCCESS"), candidateSuccess=countBy(candidate,(item)=>item.result==="TASK_SUCCESS"); if (candidateSuccess<currentSuccess+authority.contract.candidate_admission.task_success_non_inferiority.candidate_total_delta_floor) addReason(rejectReasons,"TASK_SUCCESS_NON_INFERIORITY",`${candidateSuccess} < ${currentSuccess}-1`);
  const taskMap=authority.qualification.tasks, families=new Set([...taskMap.values()].map((task)=>task.family)); for (const family of families) { const c0=countBy(current,(item)=>taskMap.get(item.task.task_id)?.family===family&&item.result==="TASK_SUCCESS"), c1=countBy(candidate,(item)=>taskMap.get(item.task.task_id)?.family===family&&item.result==="TASK_SUCCESS"); if (c1<c0+authority.contract.candidate_admission.task_success_non_inferiority.candidate_family_delta_floor) addReason(rejectReasons,"TASK_FAMILY_NON_INFERIORITY",`${family}:${c1}<${c0}-1`); }
  for (const metricId of authority.contract.critical_metric_ids) { const def=authority.contract.metric_definitions[metricId], isCritical=(value)=>metricId==="FALSE_VERIFIED"?value==="PRESENT":value==="MATERIAL"; const c0=countBy(current,(item)=>isCritical(metricValue(item,metricId))), c1=countBy(candidate,(item)=>isCritical(metricValue(item,metricId))); if (c1>c0) addReason(rejectReasons,"CRITICAL_METRIC_REGRESSION",`${metricId}:${c1}>${c0}`); const currentByTask=groupByTask(current), candidateByTask=groupByTask(candidate); for (const taskId of taskMap.keys()) { const t0=countBy(currentByTask.get(taskId) ?? [],(item)=>isCritical(metricValue(item,metricId))), t1=countBy(candidateByTask.get(taskId) ?? [],(item)=>isCritical(metricValue(item,metricId))); if (t1>=authority.contract.candidate_admission.repeated_same_task_critical_regression_threshold&&t1>t0) addReason(rejectReasons,"REPEATED_SAME_TASK_CRITICAL_REGRESSION",`${metricId}/${taskId}:${t1}>${t0}`); } if (def.admission_role!=="CRITICAL") addReason(rejectReasons,"CRITICAL_METRIC_ROLE_DRIFT",metricId); }
  for (const metricId of ["PREMATURE_CONVERGENCE","PATH_OVERCONSTRAINT"]) { const c0=countBy(current,(item)=>metricValue(item,metricId)==="MATERIAL"), c1=countBy(candidate,(item)=>metricValue(item,metricId)==="MATERIAL"); if (c1>c0+authority.contract.candidate_admission.autonomy_material_delta_ceiling) addReason(rejectReasons,"AUTONOMY_MATERIAL_REGRESSION",`${metricId}:${c1}>${c0}+1`); const currentByTask=groupByTask(current), candidateByTask=groupByTask(candidate); for (const taskId of taskMap.keys()) { const t0=countBy(currentByTask.get(taskId) ?? [],(item)=>metricValue(item,metricId)==="MATERIAL"), t1=countBy(candidateByTask.get(taskId) ?? [],(item)=>metricValue(item,metricId)==="MATERIAL"); if (t1>=2&&t1>t0) addReason(rejectReasons,"REPEATED_SAME_TASK_AUTONOMY_REGRESSION",`${metricId}/${taskId}`); } }
  const replanCurrentBad=countBy(current,(item)=>["FAILED_TO_REPLAN","UNJUSTIFIED_PLAN_CHURN"].includes(metricValue(item,"REPLANNING_COMPETENCE"))), replanCandidateBad=countBy(candidate,(item)=>["FAILED_TO_REPLAN","UNJUSTIFIED_PLAN_CHURN"].includes(metricValue(item,"REPLANNING_COMPETENCE"))); if (replanCandidateBad>replanCurrentBad) addReason(rejectReasons,"REPLANNING_REGRESSION",`${replanCandidateBad}>${replanCurrentBad}`);
  const ceremonyCurrent=countBy(current,(item)=>metricValue(item,"CEREMONY_TAX")==="MATERIAL"), ceremonyCandidate=countBy(candidate,(item)=>metricValue(item,"CEREMONY_TAX")==="MATERIAL"); if (ceremonyCandidate>ceremonyCurrent+authority.contract.candidate_admission.ceremony_material_delta_ceiling) addReason(rejectReasons,"CEREMONY_REGRESSION",`${ceremonyCandidate}>${ceremonyCurrent}+1`); for (const [taskId,task] of taskMap) { if (task.risk!=="LOW") continue; const c0=countBy(current.filter((item)=>item.task.task_id===taskId),(item)=>metricValue(item,"CEREMONY_TAX")==="MATERIAL"), c1Records=candidate.filter((item)=>item.task.task_id===taskId), c1=countBy(c1Records,(item)=>metricValue(item,"CEREMONY_TAX")==="MATERIAL"), successGain=countBy(c1Records,(item)=>item.result==="TASK_SUCCESS")-countBy(current.filter((item)=>item.task.task_id===taskId),(item)=>item.result==="TASK_SUCCESS"); if (c1>=2&&c1>c0&&successGain<2) addReason(rejectReasons,"REPEATED_LOW_RISK_CEREMONY",taskId); }
}
